language: go

go:
  - release

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi 

install:

script:
  - go test ./...
  - cd tokenizer; go test -bench .
  - /bin/sh ./go-coverall.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

#branches:
#  only:
#    - master

