language: go

go:
  - tip

sudo: false

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:

script:
  - go test ./...
  - cd tokenizer; go test -bench .;cd ..
  - /bin/sh ./go-coverall.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

